<h1>UNData API Exercise</h1>

In this exercise, you'll redo the data gathering phase of the UNData Exploration project by using APIs instead of downloading csv files.

You'll make use of the World Bank Indicators API. Note that this API does not require an API key. Before attempting the exercise, it would be a good idea to skim through the Documentation page and to check out the Basic Call Structure article.

<h2>Use the API to get all available data for the GDP per capita, PPP (constant 2021 international $) indicator.</h2>

Hint: this indicator has code "NY.GDP.PCAP.PP.KD". Adjust the query parameters so that you can retrieve all available rows. Convert the results to a DataFrame.

In [203]:
import requests
import pandas as pd
import time

In [120]:
url = "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?per_page=10000&format=json"
url2 = "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?per_page=10000&page=2&format=json"

# Send GET request
response = requests.get(url)
response2 = requests.get(url2)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    #print(response2.json())
    gdp_p1 = response.json()
    gdp_p2 = response2.json()
    gdp_p1_json = pd.json_normalize(gdp_p1[1])
    gdp_p2_json = pd.json_normalize(gdp_p2[1])
    gdp_df = pd.concat([gdp_p1_json, gdp_p2_json])
else:
    print("Request failed with status code:", response.status_code)

Request successful!

In [122]:
gdp_df.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2025,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
1,AFE,2024,4106.434140,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
2,AFE,2023,4083.993003,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
3,AFE,2022,4106.501907,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
4,AFE,2021,4056.113017,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern

<h2>Now, use the API to get all available data for Life expectancy at birth, total (years). This indicator has code "SP.DYN.LE00.IN". Again, convert the results to a DataFrame.</h2>

In [111]:
url = "https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?per_page=10000&format=json"
url2 = "https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?per_page=10000&page=2&format=json"

# Send GET request
response = requests.get(url)
response2 = requests.get(url2)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    #print(response2.json())
    lab_p1 = response.json()
    lab_p2 = response2.json()
    lab_p1_json = pd.json_normalize(lab_p1[1])
    lab_p2_json = pd.json_normalize(lab_p2[1])
    lab_df = pd.concat([lab_p1_json, lab_p2_json])
else:
    print("Request failed with status code:", response.status_code)

Request successful!

In [113]:
lab_df.tail()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
7551,ZWE,1964,55.431,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
7552,ZWE,1963,54.942,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
7553,ZWE,1962,54.453,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
7554,ZWE,1961,53.966,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
7555,ZWE,1960,53.492,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe

<h2>Merge the two results DataFrames together. You may want to rename or drop columns prior to merging.</h2>

In [ ]:
gdp_df = gdp_df.drop(columns=['unit', 'obs_status', 'decimal', 'indicator.id', 'indicator.value'])

In [126]:
gdp_df = gdp_df[['date', 'country.value', 'country.id', 'countryiso3code', 'value']]
gdp_df.head()

   date                country.value country.id countryiso3code        value
0  2025  Africa Eastern and Southern         ZH             AFE          NaN
1  2024  Africa Eastern and Southern         ZH             AFE  4106.434140
2  2023  Africa Eastern and Southern         ZH             AFE  4083.993003
3  2022  Africa Eastern and Southern         ZH             AFE  4106.501907
4  2021  Africa Eastern and Southern         ZH             AFE  4056.113017

In [128]:
gdp_df.columns = ['year', 'country', 'country_id', 'country_iso3', 'gdp_per_capita']

In [142]:
gdp_df.head()

   year                      country country_id country_iso3  gdp_per_capita
0  2025  Africa Eastern and Southern         ZH          AFE             NaN
1  2024  Africa Eastern and Southern         ZH          AFE     4106.434140
2  2023  Africa Eastern and Southern         ZH          AFE     4083.993003
3  2022  Africa Eastern and Southern         ZH          AFE     4106.501907
4  2021  Africa Eastern and Southern         ZH          AFE     4056.113017

In [131]:
lab_df = lab_df.drop(columns=['countryiso3code', 'unit', 'obs_status', 'decimal', 'indicator.id', 'indicator.value', 'country.value'])

In [148]:
lab_df.columns = ['year', 'life_expectancy_at_birth', 'country_id']
lab_df.head()

   year  life_expectancy_at_birth country_id
0  2025                       NaN         ZH
1  2024                 65.349930         ZH
2  2023                 65.146228         ZH
3  2022                 64.487152         ZH
4  2021                 62.979999         ZH

In [155]:
gdp_lab_df = pd.merge(gdp_df, lab_df, on = ['year', 'country_id'])
gdp_lab_df.head()

,year,country,country_id,country_iso3,gdp_per_capita,life_expectancy_at_birth
0,2025,Africa Eastern and Southern,ZH,AFE,NaN,NaN
1,2024,Africa Eastern and Southern,ZH,AFE,4106.434140,65.349930
2,2023,Africa Eastern and Southern,ZH,AFE,4083.993003,65.146228
3,2022,Africa Eastern and Southern,ZH,AFE,4106.501907,64.487152
4,2021,Africa Eastern and Southern,ZH,AFE,4056.113017,62.979999

<h2>You can also get more information about the available countries (region, capital city, income level classification, etc.) by using the Country API.</h2>

Use this API to pull in all available data. Merge this with your other datasets. Use this to now remove the rows that correspond to regions and not countries.

In [ ]:
url = "https://api.worldbank.org/v2/country?per_page=300&format=json"

# Send GET request
response = requests.get(url)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    print(response.json())
    countries = response.json()
    countries_df = pd.json_normalize(countries[1])
else:
    print("Request failed with status code:", response.status_code)

In [167]:
countries_df.head()

,id,iso2Code,name,capitalCity,longitude,latitude,region.id,region.iso2code,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,ABW,AW,Aruba,Oranjestad,-70.0167,12.5167,LCN,ZJ,Latin America & Caribbean,,,,HIC,XD,High income,LNX,XX,Not classified
1,AFE,ZH,Africa Eastern and Southern,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,AFR,A9,Africa,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,AFW,ZI,Africa Western and Central,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates

In [168]:
gdp_lab_countries = gdp_lab_df.merge(countries_df, left_on='country_id', right_on='iso2Code')
gdp_lab_countries.head()

,year,country,country_id,country_iso3,gdp_per_capita,life_expectancy_at_birth,id,iso2Code,name,capitalCity,...,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,2025,Africa Eastern and Southern,ZH,AFE,NaN,NaN,AFE,ZH,Africa Eastern and Southern,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
1,2024,Africa Eastern and Southern,ZH,AFE,4106.434140,65.349930,AFE,ZH,Africa Eastern and Southern,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,2023,Africa Eastern and Southern,ZH,AFE,4083.993003,65.146228,AFE,ZH,Africa Eastern and Southern,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
3,2022,Africa Eastern and Southern,ZH,AFE,4106.501907,64.487152,AFE,ZH,Africa Eastern and Southern,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,2021,Africa Eastern and Southern,ZH,AFE,4056.113017,62.979999,AFE,ZH,Africa Eastern and Southern,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates

In [169]:
print(gdp_lab_countries['region.value'].unique())

['Aggregates' 'Middle East, North Africa, Afghanistan & Pakistan'
 'Europe & Central Asia' 'East Asia & Pacific' 'Sub-Saharan Africa '
 'Latin America & Caribbean ' 'South Asia' 'North America']

In [172]:
print(gdp_lab_countries.loc[gdp_lab_countries['region.value'] == 'Aggregates']['country'].unique())

['Africa Eastern and Southern' 'Africa Western and Central' 'Arab World'
 'Caribbean small states' 'Central Europe and the Baltics'
 'Early-demographic dividend' 'East Asia & Pacific'
 'East Asia & Pacific (excluding high income)'
 'East Asia & Pacific (IDA & IBRD countries)' 'Euro area'
 'Europe & Central Asia' 'Europe & Central Asia (excluding high income)'
 'Europe & Central Asia (IDA & IBRD countries)' 'European Union'
 'Fragile and conflict affected situations'
 'Heavily indebted poor countries (HIPC)' 'High income' 'IBRD only'
 'IDA & IBRD total' 'IDA blend' 'IDA only' 'IDA total'
 'Late-demographic dividend' 'Latin America & Caribbean'
 'Latin America & Caribbean (excluding high income)'
 'Latin America & the Caribbean (IDA & IBRD countries)'
 'Least developed countries: UN classification' 'Low & middle income'
 'Low income' 'Lower middle income'
 'Middle East, North Africa, Afghanistan & Pakistan'
 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)'
 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)'
 'Middle income' 'North America' 'Not classified' 'OECD members'
 'Other small states' 'Pacific island small states'
 'Post-demographic dividend' 'Pre-demographic dividend' 'Small states'
 'South Asia' 'South Asia (IDA & IBRD)' 'Sub-Saharan Africa'
 'Sub-Saharan Africa (excluding high income)'
 'Sub-Saharan Africa (IDA & IBRD countries)' 'Upper middle income' 'World']

In [173]:
gdp_lab_countries = gdp_lab_countries.loc[gdp_lab_countries['region.value'] != 'Aggregates']
print(gdp_lab_countries['country'].unique())

['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas, The' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cabo Verde'
 'Cambodia' 'Cameroon' 'Canada' 'Cayman Islands'
 'Central African Republic' 'Chad' 'Channel Islands' 'Chile' 'China'
 'Colombia' 'Comoros' 'Congo, Dem. Rep.' 'Congo, Rep.' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt, Arab Rep.'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Faroe Islands' 'Fiji' 'Finland' 'France' 'French Polynesia'
 'Gabon' 'Gambia, The' 'Georgia' 'Germany' 'Ghana' 'Gibraltar' 'Greece'
 'Greenland' 'Grenada' 'Guam' 'Guatemala' 'Guinea' 'Guinea-Bissau'
 'Guyana' 'Haiti' 'Honduras' 'Hong Kong SAR, China' 'Hungary' 'Iceland'
 'India' 'Indonesia' 'Iran, Islamic Rep.' 'Iraq' 'Ireland' 'Isle of Man'
 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kiribati' "Korea, Dem. People's Rep." 'Korea, Rep.' 'Kosovo' 'Kuwait'
 'Kyrgyz Republic' 'Lao PDR' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia'
 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Macao SAR, China'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia, Fed. Sts.' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro'
 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria'
 'North Macedonia' 'Northern Mariana Islands' 'Norway' 'Oman' 'Pakistan'
 'Palau' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto Rico (US)' 'Qatar' 'Romania'
 'Russian Federation' 'Rwanda' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Sint Maarten (Dutch part)' 'Slovak Republic'
 'Slovenia' 'Solomon Islands' 'Somalia, Fed. Rep.' 'South Africa'
 'South Sudan' 'Spain' 'Sri Lanka' 'St. Kitts and Nevis' 'St. Lucia'
 'St. Martin (French part)' 'St. Vincent and the Grenadines' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syrian Arab Republic' 'Tajikistan'
 'Tanzania' 'Thailand' 'Timor-Leste' 'Togo' 'Tonga' 'Trinidad and Tobago'
 'Tunisia' 'Turkiye' 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu'
 'Uganda' 'Ukraine' 'United Arab Emirates' 'United Kingdom'
 'United States' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Venezuela, RB'
 'Viet Nam' 'Virgin Islands (U.S.)' 'West Bank and Gaza' 'Yemen, Rep.'
 'Zambia' 'Zimbabwe']

In [175]:
gdp_lab_countries = gdp_lab_countries.reset_index(drop=True)

In [182]:
gdp_lab_countries = gdp_lab_countries.drop(columns=['id', 'iso2Code', 'name'])

In [183]:
gdp_lab_countries.head()

,year,country,country_id,country_iso3,gdp_per_capita,life_expectancy_at_birth,capitalCity,longitude,latitude,region.id,...,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,2025,Afghanistan,AF,AFG,NaN,NaN,Kabul,69.1761,34.5228,MEA,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
1,2024,Afghanistan,AF,AFG,NaN,66.289,Kabul,69.1761,34.5228,MEA,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
2,2023,Afghanistan,AF,AFG,1983.812620,66.035,Kabul,69.1761,34.5228,MEA,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,2022,Afghanistan,AF,AFG,1981.710168,65.617,Kabul,69.1761,34.5228,MEA,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
4,2021,Afghanistan,AF,AFG,2144.166570,60.417,Kabul,69.1761,34.5228,MEA,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA

In [184]:
gdp_lab_countries.columns

Index(['year', 'country', 'country_id', 'country_iso3', 'gdp_per_capita',
       'life_expectancy_at_birth', 'capitalCity', 'longitude', 'latitude',
       'region.id', 'region.iso2code', 'region.value', 'adminregion.id',
       'adminregion.iso2code', 'adminregion.value', 'incomeLevel.id',
       'incomeLevel.iso2code', 'incomeLevel.value', 'lendingType.id',
       'lendingType.iso2code', 'lendingType.value'],
      dtype='object')

<h1>Bonus Questions</h1>

After doing a basic request to get all records, you can attempt these exercises to get additional practice using query parameters.

<h2>Adjust your request so that it returns data just for the United States.</h2>

In [ ]:
url = "https://api.worldbank.org/v2/country/us/indicator/NY.GDP.PCAP.PP.KD?format=json"

# Send GET request
response = requests.get(url)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    print(response.json())
    gdp_us_json = response.json()
    gdp_us = pd.json_normalize(gdp_us_json[1])
else:
    print("Request failed with status code:", response.status_code)

In [189]:
gdp_us.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,USA,2025,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
1,USA,2024,75489.266433,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
2,USA,2023,74158.716416,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
3,USA,2022,72679.257540,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
4,USA,2021,71307.401728,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States

<h2>Adjust your request so that it returns data just for the United States for the year 2021.</h2>

In [190]:
url = "https://api.worldbank.org/v2/country/us/indicator/NY.GDP.PCAP.PP.KD?date=2021&format=json"

# Send GET request
response = requests.get(url)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    print(response.json())
    gdp_us_2021_json = response.json()
    gdp_us_2021 = pd.json_normalize(gdp_us_2021_json[1])
else:
    print("Request failed with status code:", response.status_code)

Request successful!
[{'page': 1, 'pages': 1, 'per_page': 50, 'total': 1, 'sourceid': '2', 'lastupdated': '2026-04-08'}, [{'indicator': {'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per capita, PPP (constant 2021 international $)'}, 'country': {'id': 'US', 'value': 'United States'}, 'countryiso3code': 'USA', 'date': '2021', 'value': 71307.4017277218, 'unit': '', 'obs_status': '', 'decimal': 0}]]

In [191]:
gdp_us_2021.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,USA,2021,71307.401728,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States

<h2>Adjust your request so that it returns data just for the United States for the years 2000 through 2021.</h2>

In [ ]:
url = "https://api.worldbank.org/v2/country/us/indicator/NY.GDP.PCAP.PP.KD?date=2000:2021&format=json"

# Send GET request
response = requests.get(url)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    print(response.json())
    gdp_us_2000_2021_json = response.json()
    gdp_us_2000_2021 = pd.json_normalize(gdp_us_2000_2021_json[1])
else:
    print("Request failed with status code:", response.status_code)

In [193]:
gdp_us_2000_2021.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,USA,2021,71307.401728,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
1,USA,2020,67342.070929,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
2,USA,2019,69112.602689,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
3,USA,2018,67719.765639,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
4,USA,2017,66155.555568,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States

<h2>Adjust your request so that it returns data for the United States and Canada for the years 2000 through 2021.</h2>

In [ ]:
url = "https://api.worldbank.org/v2/country/us;ca/indicator/NY.GDP.PCAP.PP.KD?date=2000:2021&format=json"

# Send GET request
response = requests.get(url)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    print(response.json())
    gdp_us_ca_2000_2021_json = response.json()
    gdp_us_ca_2000_2021 = pd.json_normalize(gdp_us_ca_2000_2021_json[1])
else:
    print("Request failed with status code:", response.status_code)

In [195]:
gdp_us_ca_2000_2021.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,CAN,2021,56995.117678,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
1,CAN,2020,54092.879032,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
2,CAN,2019,57583.845798,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
3,CAN,2018,57337.490910,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
4,CAN,2017,56612.328537,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada

In [199]:
url = "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?format=json"

# Send GET request
response = requests.get(url)

# Check response status
if response.status_code == 200:
    print("Request successful!")
    print(response.json()[0])
else:
    print("Request failed with status code:", response.status_code)

Request successful!
{'page': 1, 'pages': 352, 'per_page': 50, 'total': 17556, 'sourceid': '2', 'lastupdated': '2026-04-08'}

In [205]:
all_data = []

for p in range(353):
    url = f"https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?page={p}&format=json"
    response = requests.get(url)

# Check response status
    if response.status_code == 200:
        print(f"Accessed Page {p}")
        all_data.append(response.json()[0])
    else:
        print("Request failed with status code:", response.status_code)
        break
    time.sleep(1)

Accessed Page 0
Accessed Page 1
Accessed Page 2
Accessed Page 3
Accessed Page 4
Accessed Page 5
Accessed Page 6
Accessed Page 7
Accessed Page 8
Accessed Page 9
Accessed Page 10
Accessed Page 11
Accessed Page 12
Accessed Page 13
Accessed Page 14
Accessed Page 15
Accessed Page 16
Accessed Page 17
Accessed Page 18
Accessed Page 19
Accessed Page 20
Accessed Page 21
Accessed Page 22
Accessed Page 23
Accessed Page 24
Request failed with status code: 400